<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <SupportedOSPlatform>linux</SupportedOSPlatform>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>SilverScreen</AssemblyName>
        <Version Condition="'$(Version)' == ''">0.1.0</Version>
        <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
        <Authors>XSilverTH</Authors>
        <Copyright>Copyright © XSilverTH</Copyright>
        <Description>A GTK 4 and Libadwaita desktop app for YouTube</Description>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/XSilverTH/SilverScreen</PackageProjectUrl>
        <RepositoryUrl>https://github.com/XSilverTH/SilverScreen.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="**\*.cs">
            <DependentUpon>%(Filename).blp</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GirCore.Adw-1"/>
        <PackageReference Include="GirCore.Soup-3.0"/>
        <PackageReference Include="GirCore.WebKit-6.0"/>
        <PackageReference Include="XSTH.Blueprint.Helpers"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="Tmds.DBus.Generator"/>
        <PackageReference Include="Tmds.DBus.Protocol"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <InternalsVisibleTo Include="SilverScreen.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Dbus/org.mpris.MediaPlayer2.xml" Namespace="SilverScreen.DBus" DBusGeneratorMode="Handler"/>
        <AdditionalFiles Include="Dbus/org.mpris.MediaPlayer2.Player.xml" Namespace="SilverScreen.DBus" DBusGeneratorMode="Handler"/>
        <AdditionalFiles Include="Dbus/org.freedesktop.portal.xml" Namespace="SilverScreen.DBus" DBusGeneratorMode="Proxy"/>
        <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="Namespace"/>
        <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="GenerateDBusTypes"/>
        <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="DBusGeneratorMode"/>
    </ItemGroup>

    <ItemGroup>
        <GResource Include="Assets\*"/>
        <GResource Include="Styles\*"/>
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\SilverScreen.Core\SilverScreen.Core.csproj"/>
        <ProjectReference Include="..\SilverScreen.Infrastructure\SilverScreen.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
