<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <ManagePackageVersionsCentrally Condition="'$(MSBuildProjectName)' == 'DiscordRPC' or '$(MSBuildProjectName)' == 'DiscordRPC.Example'">false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="GirCore.Adw-1" Version="0.8.1" />
    <PackageVersion Include="GirCore.Soup-3.0" Version="0.8.1" />
    <PackageVersion Include="GirCore.WebKit-6.0" Version="0.8.1" />
    <PackageVersion Include="XSTH.Blueprint.Helpers" Version="3.1.0" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Tmds.DBus.Generator" Version="0.95.0" />
    <PackageVersion Include="Tmds.DBus.Protocol" Version="0.95.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
